# Generated by Django 5.0.1 on 2025-04-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0002_annexallowedbyfunction_allregistereddossiers_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EFSAJECFAFOODNoNOEAL",
            new_name="EFSA_JECFAFoodNoNOEAL",
        ),
    ]
