# Generated by Django 5.0.1 on 2025-04-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_rename_efsajecfafoodnonoeal_efsa_jecfafoodnonoeal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sccsopinions",
            name="adopted_on",
            field=models.CharField(blank=True, null=True, verbose_name="Adopted on"),
        ),
    ]
