# Generated by Django 5.0.1 on 2025-04-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0004_alter_sccsopinions_adopted_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
    ]
