# Generated by Django 5.0.1 on 2025-04-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0005_alter_ingredient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.TextField(blank=True, null=True, verbose_name="Name"),
        ),
    ]
