# Generated by Django 5.0.1 on 2025-04-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0007_alter_ingredient_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toxricld50",
            name="name",
            field=models.TextField(blank=True, null=True, verbose_name="Name"),
        ),
    ]
