# Generated by Django 5.0.1 on 2025-04-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0008_alter_toxricld50_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toxricld50",
            name="is_toxicity",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Is Toxicity"
            ),
        ),
    ]
