"""Initial migration

Revision ID: 02e4f350063b
Revises: 
Create Date: 2025-07-18 18:05:24.807774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e4f350063b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_fogli_memorizzati')
    op.drop_table('t_coord_sezionatori')
    op.drop_table('t_utenze_sottocat')
    op.drop_table('t_blocchi')
    op.drop_table('t_nodi_prg')
    op.drop_table('t_componenti')
    op.drop_table('t_opzioni_avviamento')
    op.drop_table('t_hw_nodo')
    op.drop_table('t_coord_cavo_sez_mot')
    op.drop_table('t_coord_contattori')
    op.drop_table('t_coord_cavi_da_quadro')
    op.drop_table('t_utenze_cat')
    op.drop_table('t_coord_salvamotore')
    op.drop_table('t_libreria_simb')
    op.drop_table('t_utenze_opzioni')
    op.drop_table('t_tag_blocchi')
    op.drop_table('t_coord_cavi_in_quadro')
    op.drop_table('t_coord_motore')
    op.drop_table('t_blocchi_potenza')
    op.drop_table('t_coord_cavi_aux_sez')
    op.drop_table('t_coordinamento')
    op.drop_table('t_quadro')
    op.drop_table('t_coord_terminals')
    op.alter_column('t_potenza', 'tensione',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.add_column('t_utenza', sa.Column('id_nodo', sa.Integer(), nullable=True))
    op.add_column('t_utenza', sa.Column('tipo_comando', sa.String(length=50), nullable=True))
    op.add_column('t_utenza', sa.Column('id_cat', sa.Integer(), nullable=True))
    op.add_column('t_utenza', sa.Column('id_sottocat', sa.Integer(), nullable=True))
    op.add_column('t_utenza', sa.Column('id_opzione', sa.Integer(), nullable=True))
    op.add_column('t_utenza', sa.Column('elaborata', sa.Integer(), nullable=True))
    op.add_column('t_utenza', sa.Column('taglio', sa.String(length=50), nullable=True))
    op.alter_column('t_utenza', 'tensione',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_utenza', 'tensione',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('t_utenza', 'taglio')
    op.drop_column('t_utenza', 'elaborata')
    op.drop_column('t_utenza', 'id_opzione')
    op.drop_column('t_utenza', 'id_sottocat')
    op.drop_column('t_utenza', 'id_cat')
    op.drop_column('t_utenza', 'tipo_comando')
    op.drop_column('t_utenza', 'id_nodo')
    op.alter_column('t_potenza', 'tensione',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.create_table('t_coord_terminals',
    sa.Column('id_coordinamento', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('articolo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pe_terminal', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_quadro',
    sa.Column('id_quadro', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descrizione', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_quadro', name=op.f('t_quadro_pkey'))
    )
    op.create_table('t_coordinamento',
    sa.Column('id_coordinamento', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('costruttore', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tensione', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('potenza', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ampere', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tipo_avviamento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('componente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nome_tabella', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_coord_cavi_aux_sez',
    sa.Column('id_coordinamento', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('articolo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diametro', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cg_cavo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cg_diametro', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_blocchi_potenza',
    sa.Column('id_blocco_potenza', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_prg', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_utenza', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('NumeroFoglio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blocco_grafico', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Ox', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Oy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('xml', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_blocco_potenza', name=op.f('t_blocchi_potenza_pkey'))
    )
    op.create_table('t_coord_motore',
    sa.Column('id_coordinamento', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('potenza', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ampere', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('speed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('connessione', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Volt', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_coord_cavi_in_quadro',
    sa.Column('id_coordinamento', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('articolo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sezione', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('colore', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diametro', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_tag_blocchi',
    sa.Column('id_tag', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_blocco', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('nome_tag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quadro_tag', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_utenze_opzioni',
    sa.Column('id_opzione', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_sottocategoria', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('opzione', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('script_py', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('visibile', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_libreria_simb',
    sa.Column('id_simbolo', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('BlockName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sigla', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description_IT', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description_EN', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description_FR', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description_DE', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description_ES', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description_CZ', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description_PO', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description_FI', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description_HU', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description_SL', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description_PL', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('State', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('utilizzato', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Ox', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Oy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('L', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('H', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('componente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_categoria', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_sottocategoria', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo_simbolo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Blocco_Grafico', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('TipoIO', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_coord_salvamotore',
    sa.Column('id_coordinamento', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('articolo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('perdite_potenza', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aux_contacts', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kit_connection', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('morsettiera', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('size', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('campo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('settaggio', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_utenze_cat',
    sa.Column('id_categoria', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('visibile', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_coord_cavi_da_quadro',
    sa.Column('id_coordinamento', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('articolo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diametro', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cg_cavo_multi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cg_diametro', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_coord_contattori',
    sa.Column('id_coordinamento', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('articolo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('power_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('line_c_power', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('line_c_filter', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_coord_cavo_sez_mot',
    sa.Column('id_coordinamento', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('articolo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cg_cable_multi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diametro', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_hw_nodo',
    sa.Column('id_nodo_hw', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_prg', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_nodo', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_hw', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('slot', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('quantita', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_opzioni_avviamento',
    sa.Column('id_opzione', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('descrizione', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_blocco', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_componenti',
    sa.Column('id_componente', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_prg', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_utenza', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_potenza', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('componente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('padre_figlio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quadro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('taglia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('funzione1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('funzione2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('costruttore', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descrizione', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('potenza', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('xml', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_nodi_prg',
    sa.Column('id_nodo', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_prg', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('nome_nodo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descrizione', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_blocchi',
    sa.Column('id_blocco', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dwg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Ox', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Oy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('componente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descrizione', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('L', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('H', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('slot_max', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('config_path', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_utenze_sottocat',
    sa.Column('id_sottocategoria', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_categoria', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sottocategoria', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descrizione', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('visibile', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('t_coord_sezionatori',
    sa.Column('id_coordinamento', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('articolo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aux_contacts', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Ampere', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('kw_ac3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('kw_ac23', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('H_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('L_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('P_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_sezione_cavo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('t_fogli_memorizzati',
    sa.Column('id_foglio', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_prg', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_utenza', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dwg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('numero_foglio', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Ox', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Oy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('xml', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
