"""Update potenza column

Revision ID: 08594bd2a6f2
Revises: 593e77249ebe
Create Date: 2025-07-18 21:46:18.258710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08594bd2a6f2'
down_revision: Union[str, Sequence[str], None] = '593e77249ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_potenza', sa.Column('id_nodo', sa.Integer(), nullable=True))
    op.add_column('t_potenza', sa.Column('tipo', sa.String(length=50), nullable=True))
    op.add_column('t_potenza', sa.Column('DI', sa.Integer(), nullable=True))
    op.add_column('t_potenza', sa.Column('DO', sa.Integer(), nullable=True))
    op.add_column('t_potenza', sa.Column('elaborato', sa.String(length=1), nullable=True))
    op.add_column('t_potenza', sa.Column('id_opzione_avviamento', sa.Integer(), nullable=True))
    op.add_column('t_potenza', sa.Column('id_blocco', sa.Integer(), nullable=True))
    op.add_column('t_potenza', sa.Column('Ox', sa.Float(), nullable=True))
    op.add_column('t_potenza', sa.Column('Oy', sa.Float(), nullable=True))
    op.add_column('t_potenza', sa.Column('dwg', sa.String(length=50), nullable=True))
    op.add_column('t_potenza', sa.Column('L', sa.Float(), nullable=True))
    op.add_column('t_potenza', sa.Column('id_coordinamento', sa.Integer(), nullable=True))
    op.add_column('t_potenza', sa.Column('NumeroFoglio', sa.Text(), nullable=True))
    op.add_column('t_potenza', sa.Column('xml', sa.Text(), nullable=True))
    op.alter_column('t_potenza', 'nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('t_potenza', 'potenza',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('t_potenza', 'zona',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_potenza', 'zona',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('t_potenza', 'potenza',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('t_potenza', 'nome',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('t_potenza', 'xml')
    op.drop_column('t_potenza', 'NumeroFoglio')
    op.drop_column('t_potenza', 'id_coordinamento')
    op.drop_column('t_potenza', 'L')
    op.drop_column('t_potenza', 'dwg')
    op.drop_column('t_potenza', 'Oy')
    op.drop_column('t_potenza', 'Ox')
    op.drop_column('t_potenza', 'id_blocco')
    op.drop_column('t_potenza', 'id_opzione_avviamento')
    op.drop_column('t_potenza', 'elaborato')
    op.drop_column('t_potenza', 'DO')
    op.drop_column('t_potenza', 'DI')
    op.drop_column('t_potenza', 'tipo')
    op.drop_column('t_potenza', 'id_nodo')
    # ### end Alembic commands ###
