"""hardware table

Revision ID: 306232e800d9
Revises: 08594bd2a6f2
Create Date: 2025-07-18 23:13:37.632194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306232e800d9'
down_revision: Union[str, Sequence[str], None] = '08594bd2a6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_cat_hw', sa.Column('F_DI', sa.Integer(), nullable=True))
    op.add_column('t_cat_hw', sa.Column('F_DO', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_cat_hw', 'F_DO')
    op.drop_column('t_cat_hw', 'F_DI')
    # ### end Alembic commands ###
