"""Update t_fogli_memorizzati and t_libreria_simb columns

Revision ID: 593e77249ebe
Revises: 9ea84626af14
Create Date: 2025-07-18 18:38:36.756134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593e77249ebe'
down_revision: Union[str, Sequence[str], None] = '9ea84626af14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_blocchi', sa.Column('categoria', sa.String(length=50), nullable=True))
    op.add_column('t_blocchi', sa.Column('dwg', sa.String(length=50), nullable=True))
    op.add_column('t_blocchi', sa.Column('Ox', sa.Float(), nullable=True))
    op.add_column('t_blocchi', sa.Column('Oy', sa.Float(), nullable=True))
    op.add_column('t_blocchi', sa.Column('componente', sa.String(length=50), nullable=True))
    op.add_column('t_blocchi', sa.Column('descrizione', sa.Text(), nullable=True))
    op.add_column('t_blocchi', sa.Column('L', sa.Float(), nullable=True))
    op.add_column('t_blocchi', sa.Column('H', sa.Float(), nullable=True))
    op.add_column('t_blocchi', sa.Column('slot_max', sa.Integer(), nullable=True))
    op.add_column('t_blocchi', sa.Column('config_path', sa.Text(), nullable=True))
    op.add_column('t_fogli_memorizzati', sa.Column('id_foglio', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('t_fogli_memorizzati', sa.Column('id_prg', sa.Integer(), nullable=False))
    op.add_column('t_fogli_memorizzati', sa.Column('id_utenza', sa.Integer(), nullable=True))
    op.add_column('t_fogli_memorizzati', sa.Column('dwg', sa.String(length=50), nullable=True))
    op.add_column('t_fogli_memorizzati', sa.Column('numero_foglio', sa.Integer(), nullable=True))
    op.add_column('t_fogli_memorizzati', sa.Column('Ox', sa.Float(), nullable=True))
    op.add_column('t_fogli_memorizzati', sa.Column('Oy', sa.Float(), nullable=True))
    op.add_column('t_fogli_memorizzati', sa.Column('xml', sa.Text(), nullable=True))
    op.drop_column('t_fogli_memorizzati', 'id')
    op.add_column('t_libreria_simb', sa.Column('id_simbolo', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('t_libreria_simb', sa.Column('BlockName', sa.String(length=50), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('sigla', sa.String(length=10), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Description_IT', sa.String(length=100), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Description_EN', sa.String(length=100), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Description_FR', sa.String(length=100), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Description_DE', sa.String(length=100), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Description_ES', sa.String(length=100), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Description_CZ', sa.String(length=100), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Description_PO', sa.String(length=100), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Description_FI', sa.String(length=100), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Description_HU', sa.String(length=100), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Description_SL', sa.String(length=100), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Description_PL', sa.String(length=100), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('State', sa.String(length=1), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('utilizzato', sa.Integer(), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Ox', sa.Float(), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Oy', sa.Float(), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('L', sa.Float(), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('H', sa.Float(), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('componente', sa.String(length=50), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('id_categoria', sa.String(length=50), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('id_sottocategoria', sa.String(length=50), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('tipo_simbolo', sa.String(length=50), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('Blocco_Grafico', sa.String(length=50), nullable=True))
    op.add_column('t_libreria_simb', sa.Column('TipoIO', sa.String(length=50), nullable=True))
    op.drop_column('t_libreria_simb', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_libreria_simb', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('t_libreria_simb', 'TipoIO')
    op.drop_column('t_libreria_simb', 'Blocco_Grafico')
    op.drop_column('t_libreria_simb', 'tipo_simbolo')
    op.drop_column('t_libreria_simb', 'id_sottocategoria')
    op.drop_column('t_libreria_simb', 'id_categoria')
    op.drop_column('t_libreria_simb', 'componente')
    op.drop_column('t_libreria_simb', 'H')
    op.drop_column('t_libreria_simb', 'L')
    op.drop_column('t_libreria_simb', 'Oy')
    op.drop_column('t_libreria_simb', 'Ox')
    op.drop_column('t_libreria_simb', 'utilizzato')
    op.drop_column('t_libreria_simb', 'State')
    op.drop_column('t_libreria_simb', 'Description_PL')
    op.drop_column('t_libreria_simb', 'Description_SL')
    op.drop_column('t_libreria_simb', 'Description_HU')
    op.drop_column('t_libreria_simb', 'Description_FI')
    op.drop_column('t_libreria_simb', 'Description_PO')
    op.drop_column('t_libreria_simb', 'Description_CZ')
    op.drop_column('t_libreria_simb', 'Description_ES')
    op.drop_column('t_libreria_simb', 'Description_DE')
    op.drop_column('t_libreria_simb', 'Description_FR')
    op.drop_column('t_libreria_simb', 'Description_EN')
    op.drop_column('t_libreria_simb', 'Description_IT')
    op.drop_column('t_libreria_simb', 'sigla')
    op.drop_column('t_libreria_simb', 'BlockName')
    op.drop_column('t_libreria_simb', 'id_simbolo')
    op.add_column('t_fogli_memorizzati', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('t_fogli_memorizzati', 'xml')
    op.drop_column('t_fogli_memorizzati', 'Oy')
    op.drop_column('t_fogli_memorizzati', 'Ox')
    op.drop_column('t_fogli_memorizzati', 'numero_foglio')
    op.drop_column('t_fogli_memorizzati', 'dwg')
    op.drop_column('t_fogli_memorizzati', 'id_utenza')
    op.drop_column('t_fogli_memorizzati', 'id_prg')
    op.drop_column('t_fogli_memorizzati', 'id_foglio')
    op.drop_column('t_blocchi', 'config_path')
    op.drop_column('t_blocchi', 'slot_max')
    op.drop_column('t_blocchi', 'H')
    op.drop_column('t_blocchi', 'L')
    op.drop_column('t_blocchi', 'descrizione')
    op.drop_column('t_blocchi', 'componente')
    op.drop_column('t_blocchi', 'Oy')
    op.drop_column('t_blocchi', 'Ox')
    op.drop_column('t_blocchi', 'dwg')
    op.drop_column('t_blocchi', 'categoria')
    # ### end Alembic commands ###
