"""Add legacy tables from SQLite schema

Revision ID: 9ea84626af14
Revises: 02e4f350063b
Create Date: 2025-07-18 18:27:48.940703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea84626af14'
down_revision: Union[str, Sequence[str], None] = '02e4f350063b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_blocchi',
    sa.Column('id_blocco', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id_blocco')
    )
    op.create_table('t_blocchi_potenza',
    sa.Column('id_blocco_potenza', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_prg', sa.Integer(), nullable=False),
    sa.Column('id_utenza', sa.Integer(), nullable=False),
    sa.Column('NumeroFoglio', sa.Text(), nullable=True),
    sa.Column('blocco_grafico', sa.String(length=50), nullable=True),
    sa.Column('Ox', sa.Float(), nullable=True),
    sa.Column('Oy', sa.Float(), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_blocco_potenza')
    )
    op.create_table('t_componenti',
    sa.Column('id_componente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_prg', sa.Integer(), nullable=False),
    sa.Column('id_utenza', sa.Integer(), nullable=False),
    sa.Column('id_potenza', sa.Integer(), nullable=True),
    sa.Column('componente', sa.String(length=50), nullable=True),
    sa.Column('padre_figlio', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('quadro', sa.String(length=50), nullable=True),
    sa.Column('taglia', sa.String(length=20), nullable=True),
    sa.Column('funzione1', sa.String(length=50), nullable=True),
    sa.Column('funzione2', sa.String(length=50), nullable=True),
    sa.Column('costruttore', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_componente')
    )
    op.create_table('t_coordinamento',
    sa.Column('id_coordinamento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('costruttore', sa.String(length=100), nullable=False),
    sa.Column('tensione', sa.String(length=50), nullable=True),
    sa.Column('potenza', sa.Float(), nullable=False),
    sa.Column('ampere', sa.Float(), nullable=False),
    sa.Column('tipo_avviamento', sa.String(length=50), nullable=False),
    sa.Column('componente', sa.String(length=50), nullable=True),
    sa.Column('nome_tabella', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_coordinamento')
    )
    op.create_table('t_fogli_memorizzati',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_libreria_simb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_nodi_prg',
    sa.Column('id_nodo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_prg', sa.Integer(), nullable=False),
    sa.Column('nome_nodo', sa.Text(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_nodo')
    )
    op.create_table('t_opzioni_avviamento',
    sa.Column('id_opzione', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=False),
    sa.Column('id_blocco', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_opzione')
    )
    op.create_table('t_simboli_default',
    sa.Column('id_opzione', sa.Integer(), nullable=False),
    sa.Column('componente', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('id_simbolo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_opzione')
    )
    op.create_table('t_tag_blocchi',
    sa.Column('id_tag', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_blocco', sa.Integer(), nullable=True),
    sa.Column('nome_tag', sa.String(length=50), nullable=True),
    sa.Column('quadro_tag', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_tag')
    )
    op.create_table('t_utenze_cat',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('visibile', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('t_utenze_opzioni',
    sa.Column('id_opzione', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sottocategoria', sa.Integer(), nullable=False),
    sa.Column('opzione', sa.String(length=100), nullable=False),
    sa.Column('script_py', sa.String(length=255), nullable=True),
    sa.Column('config_path', sa.String(length=255), nullable=True),
    sa.Column('visibile', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_opzione')
    )
    op.create_table('t_utenze_sottocat',
    sa.Column('id_sottocategoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('sottocategoria', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('visibile', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_sottocategoria')
    )
    op.create_table('t_coord_cavi_aux_sez',
    sa.Column('id_coordinamento', sa.Integer(), nullable=False),
    sa.Column('articolo', sa.String(length=50), nullable=True),
    sa.Column('diametro', sa.Float(), nullable=True),
    sa.Column('cg_cavo', sa.String(length=50), nullable=True),
    sa.Column('cg_diametro', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_coordinamento'], ['t_coordinamento.id_coordinamento'], ),
    sa.PrimaryKeyConstraint('id_coordinamento')
    )
    op.create_table('t_coord_cavi_da_quadro',
    sa.Column('id_coordinamento', sa.Integer(), nullable=False),
    sa.Column('articolo', sa.String(length=50), nullable=True),
    sa.Column('diametro', sa.Float(), nullable=True),
    sa.Column('cg_cavo_multi', sa.String(length=50), nullable=True),
    sa.Column('cg_diametro', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_coordinamento'], ['t_coordinamento.id_coordinamento'], ),
    sa.PrimaryKeyConstraint('id_coordinamento')
    )
    op.create_table('t_coord_cavi_in_quadro',
    sa.Column('id_coordinamento', sa.Integer(), nullable=False),
    sa.Column('articolo', sa.String(length=50), nullable=True),
    sa.Column('sezione', sa.Float(), nullable=True),
    sa.Column('colore', sa.String(length=50), nullable=True),
    sa.Column('diametro', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_coordinamento'], ['t_coordinamento.id_coordinamento'], ),
    sa.PrimaryKeyConstraint('id_coordinamento')
    )
    op.create_table('t_coord_cavo_sez_mot',
    sa.Column('id_coordinamento', sa.Integer(), nullable=False),
    sa.Column('articolo', sa.String(length=50), nullable=True),
    sa.Column('cg_cable_multi', sa.String(length=50), nullable=True),
    sa.Column('diametro', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_coordinamento'], ['t_coordinamento.id_coordinamento'], ),
    sa.PrimaryKeyConstraint('id_coordinamento')
    )
    op.create_table('t_coord_contattori',
    sa.Column('id_coordinamento', sa.Integer(), nullable=False),
    sa.Column('articolo', sa.String(length=50), nullable=True),
    sa.Column('power_loss', sa.Float(), nullable=True),
    sa.Column('line_c_power', sa.Float(), nullable=True),
    sa.Column('line_c_filter', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_coordinamento'], ['t_coordinamento.id_coordinamento'], ),
    sa.PrimaryKeyConstraint('id_coordinamento')
    )
    op.create_table('t_coord_motore',
    sa.Column('id_coordinamento', sa.Integer(), nullable=False),
    sa.Column('potenza', sa.String(length=50), nullable=True),
    sa.Column('ampere', sa.String(length=50), nullable=True),
    sa.Column('speed', sa.String(length=50), nullable=True),
    sa.Column('connessione', sa.String(length=50), nullable=True),
    sa.Column('Volt', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_coordinamento'], ['t_coordinamento.id_coordinamento'], ),
    sa.PrimaryKeyConstraint('id_coordinamento')
    )
    op.create_table('t_coord_salvamotore',
    sa.Column('id_coordinamento', sa.Integer(), nullable=False),
    sa.Column('articolo', sa.String(length=50), nullable=True),
    sa.Column('perdite_potenza', sa.String(length=50), nullable=True),
    sa.Column('aux_contacts', sa.String(length=50), nullable=True),
    sa.Column('kit_connection', sa.String(length=50), nullable=True),
    sa.Column('morsettiera', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('campo', sa.String(length=50), nullable=True),
    sa.Column('settaggio', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_coordinamento'], ['t_coordinamento.id_coordinamento'], ),
    sa.PrimaryKeyConstraint('id_coordinamento')
    )
    op.create_table('t_coord_sezionatori',
    sa.Column('id_coordinamento', sa.Integer(), nullable=False),
    sa.Column('articolo', sa.String(length=50), nullable=True),
    sa.Column('aux_contacts', sa.String(length=50), nullable=True),
    sa.Column('Ampere', sa.Float(), nullable=True),
    sa.Column('kw_ac3', sa.Float(), nullable=True),
    sa.Column('kw_ac23', sa.Float(), nullable=True),
    sa.Column('H_mm', sa.Float(), nullable=True),
    sa.Column('L_mm', sa.Float(), nullable=True),
    sa.Column('P_mm', sa.Float(), nullable=True),
    sa.Column('max_sezione_cavo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_coordinamento'], ['t_coordinamento.id_coordinamento'], ),
    sa.PrimaryKeyConstraint('id_coordinamento')
    )
    op.create_table('t_coord_terminals',
    sa.Column('id_coordinamento', sa.Integer(), nullable=False),
    sa.Column('articolo', sa.String(length=50), nullable=True),
    sa.Column('power_loss', sa.Float(), nullable=True),
    sa.Column('pe_terminal', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_coordinamento'], ['t_coordinamento.id_coordinamento'], ),
    sa.PrimaryKeyConstraint('id_coordinamento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_coord_terminals')
    op.drop_table('t_coord_sezionatori')
    op.drop_table('t_coord_salvamotore')
    op.drop_table('t_coord_motore')
    op.drop_table('t_coord_contattori')
    op.drop_table('t_coord_cavo_sez_mot')
    op.drop_table('t_coord_cavi_in_quadro')
    op.drop_table('t_coord_cavi_da_quadro')
    op.drop_table('t_coord_cavi_aux_sez')
    op.drop_table('t_utenze_sottocat')
    op.drop_table('t_utenze_opzioni')
    op.drop_table('t_utenze_cat')
    op.drop_table('t_tag_blocchi')
    op.drop_table('t_simboli_default')
    op.drop_table('t_opzioni_avviamento')
    op.drop_table('t_nodi_prg')
    op.drop_table('t_libreria_simb')
    op.drop_table('t_fogli_memorizzati')
    op.drop_table('t_coordinamento')
    op.drop_table('t_componenti')
    op.drop_table('t_blocchi_potenza')
    op.drop_table('t_blocchi')
    # ### end Alembic commands ###
