# Generated by Django 5.0.1 on 2025-04-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttype",
            name="est_qx",
        ),
        migrations.AddField(
            model_name="producttype",
            name="calculated_daily_exposure_product",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Calculated Daily Exposure Product"
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="calculated_relative_daily_exposure_product",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Calculated Relative Daily Exposure Product",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="estimated_daily_amount_applied_qx",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Estimated Amount"
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="frequency_of_application",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Frequency of Application",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="relative_daily_amount_applied_qx",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Relative Amount"
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="retention_factor_fret",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Retention Factor"
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="surface_area_for_application",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Surface Area for Application"
            ),
        ),
    ]
