# Generated by Django 5.0.1 on 2025-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_producttype_est_qx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Product Name"
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="estimated_daily_amount_applied_qx",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Estimated Daily Amount Applied",
            ),
        ),
    ]
